# Write the correct utils.js with proper HTML entity mappings
# The map values MUST be HTML entity strings: & < > "

content = (
    "/**\n"
    " * Shared Utility Functions\n"
    " * Common utilities used across modules to avoid duplication\n"
    " */\n"
    "\n"
    "/**\n"
    " * Escape HTML special characters\n"
    " */\n"
    "export function escapeHtml(text) {\n"
    "    if (text === null || text === undefined) return '';\n"
    "    const str = String(text);\n"
    "    const map = {\n"
    "        '&': '&',\n"
    "        '<': '<',\n"
    "        '>': '>',\n"
    "        '\"': '\"',\n"
    "        \"'\": '&#039;',\n"
    "        '`': '&#96;'\n"
    "    };\n"
    "    return str.replace(/[&<>\"'`]/g, m => map[m]);\n"
    "}\n"
    "\n"
    "/**\n"
    " * Generate a UUID v4 (alias for generateId)\n"
    " */\n"
    "export function generateUUID() {\n"
    "    if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {\n"
    "        return crypto.randomUUID();\n"
    "    }\n"
    "    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {\n"
    "        const r = Math.random() * 16 | 0;\n"
    "        return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);\n"
    "    });\n"
    "}\n"
    "\n"
    "// Alias for backward compatibility\n"
    "export const generateId = generateUUID;\n"
    "\n"
    "/**\n"
    " * Format currency amount with symbol\n"
    " */\n"
    "export function formatCurrency(amount, currency = 'USD') {\n"
    "    const symbols = {\n"
    "        'USD': '$',\n"
    "        'EUR': '\\u20AC',\n"
    "        'GBP': '\\u00A3',\n"
    "        'CAD': 'C$',\n"
    "        'AUD': 'A$',\n"
    "        'INR': '\\u20B9',\n"
    "        'JPY': '\\u00A5'\n"
    "    };\n"
    "    const symbol = symbols[currency] || currency;\n"
    "    const decimals = currency === 'JPY' ? 0 : 2;\n"
    "    return symbol + amount.toFixed(decimals);\n"
    "}\n"
    "\n"
    "/**\n"
    " * Get currency symbol\n"
    " */\n"
    "export function getCurrencySymbol(currency = 'USD') {\n"
    "    const symbols = {\n"
    "        'USD': '$',\n"
    "        'EUR': '\\u20AC',\n"
    "        'GBP': '\\u00A3',\n"
    "        'CAD': 'C$',\n"
    "        'AUD': 'A$',\n"
    "        'INR': '\\u20B9',\n"
    "        'JPY': '\\u00A5'\n"
    "    };\n"
    "    return symbols[currency] || currency;\n"
    "}\n"
    "\n"
    "/**\n"
    " * Deep clone an object\n"
    " */\n"
    "export function deepClone(obj) {\n"
    "    return JSON.parse(JSON.stringify(obj));\n"
    "}\n"
    "\n"
    "/**\n"
    " * Debounce function\n"
    " */\n"
    "export function debounce(fn, delay) {\n"
    "    let timeoutId;\n"
    "    return (...args) => {\n"
    "        clearTimeout(timeoutId);\n"
    "        timeoutId = setTimeout(() => fn.apply(this, args), delay);\n"
    "    };\n"
    "}\n"
    "\n"
    "/**\n"
    " * Throttle function\n"
    " */\n"
    "export function throttle(fn, limit) {\n"
    "    let inThrottle;\n"
    "    return (...args) => {\n"
    "        if (!inThrottle) {\n"
    "            fn.apply(this, args);\n"
    "            inThrottle = true;\n"
    "            setTimeout(() => inThrottle = false, limit);\n"
    "        }\n"
    "    };\n"
    "}\n"
    "\n"
    "/**\n"
    " * Parse float safely\n"
    " */\n"
    "export function parseFloatSafe(val, fallback = 0) {\n"
    "    const parsed = parseFloat(val);\n"
    "    return isNaN(parsed) ? fallback : parsed;\n"
    "}\n"
    "\n"
    "/**\n"
    " * Check if value is a valid positive number\n"
    " */\n"
    "export function isPositiveNumber(val) {\n"
    "    const num = parseFloat(val);\n"
    "    return !isNaN(num) && num >= 0;\n"
    "}\n"
    "\n"
    "/**\n"
    " * Format date with timezone support\n"
    " */\n"
    "export function formatDate(dateString, timeZone, locale) {\n"
    "    if (!dateString) return '';\n"
    "    const date = new Date(dateString + 'T00:00:00Z');\n"
    "    const resolvedLocale = locale || (typeof navigator !== 'undefined' ? navigator.language : 'en-US');\n"
    "    const resolvedTimeZone = timeZone || Intl.DateTimeFormat().resolvedOptions().timeZone;\n"
    "    return date.toLocaleDateString(resolvedLocale, {\n"
    "        year: 'numeric',\n"
    "        month: 'long',\n"
    "        day: 'numeric',\n"
    "        timeZone: resolvedTimeZone\n"
    "    });\n"
    "}\n"
    "\n"
    "/**\n"
    " * Sanitize URL for safe protocols\n"
    " */\n"
    "export function sanitizeUrl(url) {\n"
    "    if (!url) return '';\n"
    "    const trimmed = url.trim().toLowerCase();\n"
    "    const allowedProtocols = ['http:', 'https:', 'data:image/'];\n"
    "    const isAllowed = allowedProtocols.some(proto => trimmed.startswith(proto));\n"
    "    if (!isAllowed) return '';\n"
    "    return escapeHtml(url);\n"
    "}\n"
    "\n"
    "/**\n"
    " * Generate invoice number with prefix/format\n"
    " */\n"
    "export function generateInvoiceNumber(prefix = 'INV', format = 'PREFIX-XXX', startNumber = 1) {\n"
    "    const now = new Date();\n"
    "    const padLen = format.replace('PREFIX', '').match(/X+/g)?.[0]?.length || 3;\n"
    "    const paddedNumber = startNumber.toString().padStart(padLen, '0');\n"
    "    return format\n"
    "        .replace('PREFIX', prefix)\n"
    "        .replace(/X+/g, paddedNumber)\n"
    "        .replace('YYYY', now.getFullYear().toString())\n"
    "        .replace('MM', (now.getMonth() + 1).toString().padStart(2, '0'));\n"
    "}\n"
)

with open('/mnt/d/CODE/Invoice generator/js/utils.js', 'w') as f:
    f.write(content)

print('Done')